### ISSUE TITLE
make seats sittable

### ISSUE THREAD

**Issue by shaperka** [porkbrain/dont-count-the-sheep#176]
n14 in winnies atlas for animation
assign sittable to

chair_orange.png
chair_purple.png
chair_yellow.png
meditation_chair.png
sofa_purple.png
sofa_purple_plain.png
sofa_purple_plain_back.png
sofa_yellow.png
sofa_yellow_plain.png
lavicka.png

**Comment by porkbrain** [comment]
Keeping the TODO in the code base as part of migrating effort
