### ISSUE TITLE
crow animation

### ISSUE THREAD

**Issue by shaperka** [porkbrain/dont-count-the-sheep#184]
new atlas is up in the game files, 1 idle, 2 kvak, 3+4 flight, 4+5 zobani, 6+7 walking
maybe the triggering of fly away animation when player is close but also we could do a little thing where you leave out shinies for him and after a certain amount he doesn't fly away and thanks you for the shinies

**Comment by porkbrain** [comment]
Keeping the TODO in the code base as part of migrating effort
